# Generated by Django 4.0.6 on 2022-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cargo_ativo_alter_cargo_modificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(max_length=100, verbose_name='Serviço'),
        ),
    ]
